#define L0x04_GetIndexedPlayingTrackInfo            0x0C
#define L0x04_RequestProtocolVersion                0x12
#define L0x04_ResetDBSelection                      0x16
#define L0x04_SelectDBRecord                        0x17
#define L0x04_GetNumberCategorizedDBRecords         0x18
#define L0x04_RetrieveCategorizedDatabaseRecords    0x1A
#define L0x04_GetPlayStatus                         0x1C
#define L0x04_GetCurrentPlayingTrackIndex           0x1E
#define L0x04_GetIndexedPlayingTrackTitle           0x20
#define L0x04_GetIndexedPlayingTrackArtistName      0x22
#define L0x04_GetIndexedPlayingTrackAlbumName       0x24
#define L0x04_SetPlayStatusChangeNotification       0x26
#define L0x04_PlayControl                           0x29
#define L0x04_GetShuffle                            0x2C
#define L0x04_SetShuffle                            0x2E
#define L0x04_GetRepeat                             0x2F
#define L0x04_SetRepeat                             0x31
#define L0x04_GetNumPlayingTracks                   0x35
#define L0x04_SetCurrentPlayingTrack                0x37
